language: ruby
rvm: 2.3
install:
  - gem install awestruct bootstrap-sass haml-contrib maruku
script:
  - awestruct -P production
deploy:
  provider: script
  script: ./_deploy.sh
  skip_cleanup: true
  on:
    repo: togglz/togglz-site
    branch: master
env:
  global:
    secure: gLlQaGDzWPYgKI4CPo0C2HPJMNMWCgfK6bKYQ23renvXkYuqkExHcDJt9kUPsMsF4F4dUCDy93dzsca0foa0zHyqXqCVeYcP9e8IfSxRtdlBPmkeUkn6EImbG6pqmhVJZrOpwnfnCwY6A/DhSnkWDM5BBe/VQ7a1ClctO9kxZgA=
